# Detecção de Fraudes em Transações

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [5]:
url = 'https://storage.googleapis.com/download.tensorflow.org/data/creditcard.csv'

df = pd.read_csv(url)
df.head()
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

# Problema de Classificação Desbalanceada

In [6]:
df['Class'].value_counts(normalize=True)

Class
0    0.998273
1    0.001727
Name: proportion, dtype: float64

# Feature Engineering

Criando variáveis para melhora do modelo

In [7]:
# Aplicando uma transformação logaritmica nos elementos

df['Amount_log'] = np.log1p(df['Amount'])
df['Amount_log']

0         5.014760
1         1.305626
2         5.939276
3         4.824306
4         4.262539
            ...
284802    0.570980
284803    3.249987
284804    4.232366
284805    2.397895
284806    5.384495
Name: Amount_log, Length: 284807, dtype: float64

In [15]:
scalar = StandardScaler()
df['Amount_Scaled'] = scalar.fit_transform(df[['Amount']])
df['Amount_Scaled']

0         0.244964
1        -0.342475
2         1.160686
3         0.140534
4        -0.073403
            ...
284802   -0.350151
284803   -0.254117
284804   -0.081839
284805   -0.313249
284806    0.514355
Name: Amount_Scaled, Length: 284807, dtype: float64

In [16]:
x = df.drop('Class', axis=1) # Variáveis de Entradas
y = df['Class'] # Variável Target

x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=.3, random_state=42)

# Logistic Regression

In [10]:
resultado = df.loc[df['Class'] == 1, ['Time']]
resultado

            Time
541        406.0
623        472.0
4920      4462.0
6108      6986.0
6329      7519.0
...          ...
279863  169142.0
280143  169347.0
280149  169351.0
281144  169966.0
281674  170348.0

[492 rows x 1 columns]